### PR TITLE
Invocation details, copyable wamp_events, throw exception on socket rx error

### PR DESCRIPTION
**Pull request by stopthatcow**
This PR adds deserialization of the WAMP details field (field 3) in the INVOCATION message and exposes it as a key value map in the invocation object. This is useful for prefixed matched registrations that need to know the actual procedure called in order to process the call. The PR also makes wamp_events copyable in the same manner as wamp_invocations. Lastly, this PR provides a boost signal that is fired when an RX error is encountered on the session's socket.

### CODE REVIEW

**Comment by jpetso** [comment]
Independent of the actual code in the commits, do you guys think we should open PRs with tavendo/AutobahnCpp instead now that the code from this fork has been merged back?

**Comment by davidchappelle** [comment]
Yes I think it does. I was going to suggest it however it looked like a bit
of Nicholas's code depends on the components which Tobias should be merging
back shortly. I would say as soon as Tobias merges them Nicholas could fork
from there and move his commits over.

**Comment by stopthatcow** [comment]
So @davidchappelle can you point me to the PR I should be watching for tavendo's repo? After that is merged I can submit a PR back to that repo.

**Comment by davidchappelle** [comment]
This is the pull request to watch:

```
https://github.com/tavendo/AutobahnCpp/pull/55
```

**Comment by stopthatcow** [comment]
So @davidchappelle as I understand it this will not be merging back to tavendo's repo in the immediate future? I have an additional branch that adds proper capturing of wamp_error args/kwargs into a custom exception type. Should I fix up this PR and then open that one as well?

**Comment by davidchappelle** [comment]
Please pull in my latest fork before working on any further error handling. I had to refactor a bunch of the internals in order to abstract out transports. Once you are synched up lets discuss what additional error handling you are looking to add.

I have been working with @oberstet on moving forward with autobahn-cpp and corresponding api changes. It will likely be a while before this fork gets merged but it is inline with the direction that the main project is moving.

**Comment by davidchappelle** [comment]
My branch was merged back to tavendo's master. All pull requests should now
be based off of their master.

**Pull request closed without merging**
